hw3 completed
strrust/Rustam_Saitov pull request #3
Opened 2021-05-12 13:42 UTC by strrust

2021-05-14 10:52 UTC, komyagin requested changes

2021-05-14 10:52 UTC, komyagin commented on src/test/java/ru/training/at/hw3/DefaultTest.java
> +public abstract class DefaultTest {
It's not good name for common class

2021-05-14 10:52 UTC, komyagin commented on src/test/java/ru/training/at/hw3/GetDataFromProperties.java
> +public class GetDataFromProperties {
Don't use verbs in the class name. PropertiesLoader maybe?

2021-05-14 10:52 UTC, komyagin commented on src/test/java/ru/training/at/hw3/ex1/HomePageTest.java
> +        loginWindow.inputName(GetDataFromProperties.getProperty("loginName"));
You can import static method getProperty()

2021-05-14 12:13 UTC, strrust commented on src/test/java/ru/training/at/hw3/DefaultTest.java
> +public abstract class DefaultTest {
Renamed to TestBase

2021-05-14 12:13 UTC, strrust commented on src/test/java/ru/training/at/hw3/GetDataFromProperties.java
> +public class GetDataFromProperties {
good suggestion! renamed to PropertiesLoader

2021-05-14 12:13 UTC, strrust commented on src/test/java/ru/training/at/hw3/ex1/HomePageTest.java
> +        loginWindow.inputName(GetDataFromProperties.getProperty("loginName"));
Changed

2021-05-17 11:16 UTC, komyagin approved these changes

2021-05-17 11:28 UTC, merged