hw6 completed
strrust/Rustam_Saitov pull request #6
Opened 2021-05-29 10:37 UTC by strrust

2021-05-31 16:29 UTC, shoggy requested changes

2021-05-31 16:29 UTC, shoggy commented on src/main/java/ru/training/at/hw6/forms/JdiMetalsColorsForm.java
> +        int i;
This variable is not used outside of loops, I think there is no need to put it to such wide scope

2021-05-31 16:29 UTC, shoggy commented on src/main/java/ru/training/at/hw6/forms/JdiMetalsColorsForm.java
> +    public void fillInMetalsColorsForm(MetalsColorsTestData data) {
`Form` class has a special method for this type of action, override it, please

2021-05-31 16:29 UTC, shoggy commented on src/main/java/ru/training/at/hw6/pages/JdiHomePage.java
> +    }
page objects layer should not contain assertions

\+ same for another classes

2021-06-01 16:43 UTC, strrust commented on src/main/java/ru/training/at/hw6/forms/JdiMetalsColorsForm.java
> +        int i;
Replaced var init to cycles scope only

2021-06-01 16:43 UTC, strrust commented on src/main/java/ru/training/at/hw6/forms/JdiMetalsColorsForm.java
> +    public void fillInMetalsColorsForm(MetalsColorsTestData data) {
overrided like a fill method

2021-06-01 16:44 UTC, strrust commented on src/main/java/ru/training/at/hw6/pages/JdiHomePage.java
> +    }
assertions was moved to test directly

2021-06-01 20:08 UTC, shoggy approved these changes

2021-06-02 10:34 UTC, merged